// const countryMap: Record<string, string> = {
//   afghanistan: 'AF',
//   albania: 'AL',
//   algeria: 'DZ',
//   andorra: 'AD',
//   angola: 'AO',
//   antigua: 'AG',
//   argentina: 'AR',
//   armenia: 'AM',
//   australia: 'AU',
//   austria: 'AT',
//   azerbaijan: 'AZ',
//   bahamas: 'BS',
//   bahrain: 'BH',
//   bangladesh: 'BD',
//   barbados: 'BB',
//   belarus: 'BY',
//   belgium: 'BE',
//   belize: 'BZ',
//   benin: 'BJ',
//   bhutan: 'BT',
//   bolivia: 'BO',
//   bosnia: 'BA',
//   botswana: 'BW',
//   brazil: 'BR',
//   brunei: 'BN',
//   bulgaria: 'BG',
//   burkina: 'BF',
//   burundi: 'BI',
//   cabo verde: 'CV',
//   cambodia: 'KH',
//   cameroon: 'CM',
//   canada: 'CA',
//   chad: 'TD',
//   chile: 'CL',
//   china: 'CN',
//   colombia: 'CO',
//   comoros: 'KM',
//   congo: 'CG',
//   'congo democratic republic': 'CD',
//   costa rica: 'CR',
//   croatia: 'HR',
//   cuba: 'CU',
//   cyprus: 'CY',
//   czechia: 'CZ',
//   denmark: 'DK',
//   djibouti: 'DJ',
//   dominica: 'DM',
//   'dominican republic': 'DO',
//   ecuador: 'EC',
//   egypt: 'EG',
//   'el salvador': 'SV',
//   equatorial guinea: 'GQ',
//   eritrea: 'ER',
//   estonia: 'EE',
//   eswatini: 'SZ',
//   ethiopia: 'ET',
//   fiji: 'FJ',
//   finland: 'FI',
//   france: 'FR',
//   gabon: 'GA',
//   gambia: 'GM',
//   georgia: 'GE',
//   germany: 'DE',
//   ghana: 'GH',
//   greece: 'GR',
//   grenada: 'GD',
//   guatemala: 'GT',
//   guinea: 'GN',
//   'guinea-bissau': 'GW',
//   guyana: 'GY',
//   haiti: 'HT',
//   honduras: 'HN',
//   hungary: 'HU',
//   iceland: 'IS',
//   india: 'IN',
//   indonesia: 'ID',
//   iran: 'IR',
//   iraq: 'IQ',
//   ireland: 'IE',
//   israel: 'IL',
//   italy: 'IT',
//   jamaica: 'JM',
//   japan: 'JP',
//   jordan: 'JO',
//   kazakhstan: 'KZ',
//   kenya: 'KE',
//   kiribati: 'KI',
//   korea: 'KR',
//   'north korea': 'KP',
//   'south korea': 'KR',
//   kuwait: 'KW',
//   kyrgyzstan: 'KG',
//   laos: 'LA',
//   latvia: 'LV',
//   lebanon: 'LB',
//   lesotho: 'LS',
//   liberia: 'LR',
//   libya: 'LY',
//   liechtenstein: 'LI',
//   lithuania: 'LT',
//   luxembourg: 'LU',
//   macedonia: 'MK',
//   madagascar: 'MG',
//   malawi: 'MW',
//   malaysia: 'MY',
//   maldives: 'MV',
//   mali: 'ML',
//   malta: 'MT',
//   marshall islands: 'MH',
//   martinique: 'MQ',
//   mauritania: 'MR',
//   mauritius: 'MU',
//   mexico: 'MX',
//   micronesia: 'FM',
//   moldova: 'MD',
//   monaco: 'MC',
//   mongolia: 'MN',
//   montenegro: 'ME',
//   morocco: 'MA',
//   mozambique: 'MZ',
//   myanmar: 'MM',
//   namibia: 'NA',
//   nauru: 'NR',
//   nepal: 'NP',
//   netherlands: 'NL',
//   new zealand: 'NZ',
//   nicaragua: 'NI',
//   niger: 'NE',
//   nigeria: 'NG',
//   norway: 'NO',
//   oman: 'OM',
//   pakistan: 'PK',
//   palau: 'PW',
//   palestine: 'PS',
//   panama: 'PA',
//   papua new guinea: 'PG',
//   paraguay: 'PY',
//   peru: 'PE',
//   philippines: 'PH',
//   poland: 'PL',
//   portugal: 'PT',
//   puerto rico: 'PR',
//   qatar: 'QA',
//   romania: 'RO',
//   russia: 'RU',
//   rwanda: 'RW',
//   saint kitts: 'KN',
//   saint lucia: 'LC',
//   saint vincent: 'VC',
//   samoa: 'WS',
//   san marino: 'SM',
//   sao tome: 'ST',
//   saudi arabia: 'SA',
//   senegal: 'SN',
//   serbia: 'RS',
//   seychelles: 'SC',
//   sierra leone: 'SL',
//   singapore: 'SG',
//   slovakia: 'SK',
//   slovenia: 'SI',
//   solomon islands: 'SB',
//   somalia: 'SO',
//   south africa: 'ZA',
//   south sudan: 'SS',
//   spain: 'ES',
//   sri lanka: 'LK',
//   sudan: 'SD',
//   suriname: 'SR',
//   sweden: 'SE',
//   switzerland: 'CH',
//   syria: 'SY',
//   taiwan: 'TW',
//   tajikistan: 'TJ',
//   tanzania: 'TZ',
//   thailand: 'TH',
//   timor-leste: 'TL',
//   togo: 'TG',
//   tonga: 'TO',
//   trinidad: 'TT',
//   tunisia: 'TN',
//   turkey: 'TR',
//   turkmenistan: 'TM',
//   tuvalu: 'TV',
//   uganda: 'UG',
//   ukraine: 'UA',
//   'united arab emirates': 'AE',
//   'united kingdom': 'GB',
//   'united states': 'US',
//   uruguay: 'UY',
//   uzbekistan: 'UZ',
//   vanuatu: 'VU',
//   venezuela: 'VE',
//   vietnam: 'VN',
//   yemen: 'YE',
//   zambia: 'ZM',
//   zimbabwe: 'ZW',
// };

// export function normalizeCountry(input: string): string {
//   const key = input.trim().toLowerCase();
//   return countryMap[key] ?? input.toUpperCase().slice(0, 2);
// }

import countries from 'i18n-iso-countries';

countries.registerLocale(require('i18n-iso-countries/langs/en.json'));

export function normalizeCountry(input: string): string {
  const alpha2 = countries.getAlpha2Code(input.trim(), 'en');
  return alpha2 ?? input.toUpperCase().slice(0, 2);
}
